name: Deploy Hexo Blog to GitHub Pages

on:
  push:
    branches: [ main ]  # 推送到 main 分支时触发

jobs:
  # 任务1: 构建
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # 请确认与你本地 Node.js 版本一致

      - name: Install dependencies & generate
        run: |
          npm install -g hexo-cli
          npm install
          hexo generate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 任务2: 部署到 GitHub Pages
  deploy-to-github-pages:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4